#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const widgetDist = resolve(here, '../../widget/dist/widget.iife.js');
const out = resolve(here, '../src/__generated__/widget.ts');

if (!existsSync(widgetDist)) {
  console.error(
    `[pinagent:next] widget bundle not found at ${widgetDist}. Run \`pnpm --filter @pinagent/widget build\` first.`,
  );
  process.exit(1);
}

const code = readFileSync(widgetDist, 'utf8');
const escaped = JSON.stringify(code);

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/embed-widget.mjs. Do not edit.\nexport const WIDGET_SOURCE: string = ${escaped};\n`,
);

console.log(`[pinagent:next] embedded widget (${code.length} bytes) → ${out}`);
